[metadata]
version = "1.0"

[versions]

# polocloud-version
polocloud = "3.0.0-pre.8-SNAPSHOT"

# libraries
gson = "2.13.2"
oshi="6.9.1"

# platforms
velocity = "3.4.0-SNAPSHOT"
waterdog = "2.0.4-SNAPSHOT"
bungeecord = "1.21-R0.4"
spigot = "1.21.5-R0.1-SNAPSHOT"
fabric = "0.16.14"
fabric-language-kotlin = "1.13.4+kotlin.2.2.0"
nukkit = "1.0-SNAPSHOT"

npc-bukkit = "3.0.0-beta.16"

# bStats
bstats = "3.1.0"

# placeholder api
placeholderapi = "2.11.6"

# utils
lombok = "1.18.42"

# nrc
nrc-server-api = "0.1.1"

[libraries]

# polocloud
polocloud-proto =  { group = "dev.httpmarco.polocloud", name = "proto", version.ref = "polocloud" }
polocloud-sdk-java = { group = "dev.httpmarco.polocloud", name = "sdk-java", version.ref = "polocloud" }

# libraries
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
oshi = { group = "com.github.oshi", name = "oshi-core", version.ref = "oshi" }

# platforms
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
waterdog = { group = "dev.waterdog.waterdogpe", name = "waterdog", version.ref = "waterdog"}
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
nukkit = { group = "cn.nukkit", name = "nukkit", version.ref = "nukkit" }

fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

npc-bukkit = { group = "io.github.juliarn", name = "npc-lib-bukkit", version.ref = "npc-bukkit" }

# bStats
bstats-spigot = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
bstats-velocity = { group = "org.bstats", name = "bstats-velocity", version.ref = "bstats" }
bstats-bungeecord = { group = "org.bstats", name = "bstats-bungeecord", version.ref = "bstats" }

# placeholder api
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }

# utils
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# nrc
nrc-core = { group = "gg.norisk", name = "nrc-server-api-core", version.ref = "nrc-server-api" }
nrc-paper = { group = "gg.norisk", name = "nrc-server-api-paper", version.ref = "nrc-server-api" }
nrc-velocity = { group = "gg.norisk", name = "nrc-server-api-velocity", version.ref = "nrc-server-api" }
nrc-spigot = { group = "gg.norisk", name = "nrc-server-api-spigot", version.ref = "nrc-server-api" }
nrc-bungeecord = { group = "gg.norisk", name = "nrc-server-api-bungeecord", version.ref = "nrc-server-api" }

[bundles]
nrc = ["nrc-core", "nrc-paper", "nrc-velocity", "nrc-spigot", "nrc-bungeecord"]